# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class YOLOv6s(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(YOLOv6s, self).__init__()
        self.module_0 = py_nndct.nn.Input() #YOLOv6s::input_0(YOLOv6s::nndct_input_0)
        self.module_1 = py_nndct.nn.Conv2d(in_channels=3, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/RepConv[repconv1]/Conv2d[conv]/ret.3(YOLOv6s::nndct_conv2d_1)
        self.module_2 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/RepConv[repconv1]/LeakyReLU[act]/ret.7(YOLOv6s::nndct_leaky_relu_2)
        self.module_3 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepConv[0]/Conv2d[conv]/ret.9(YOLOv6s::nndct_conv2d_3)
        self.module_4 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepConv[0]/LeakyReLU[act]/ret.13(YOLOv6s::nndct_leaky_relu_4)
        self.module_5 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.15(YOLOv6s::nndct_conv2d_5)
        self.module_6 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.19(YOLOv6s::nndct_leaky_relu_6)
        self.module_7 = py_nndct.nn.Conv2d(in_channels=32, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.21(YOLOv6s::nndct_conv2d_7)
        self.module_8 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.25(YOLOv6s::nndct_leaky_relu_8)
        self.module_9 = py_nndct.nn.BatchNorm(num_features=32, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.27(YOLOv6s::nndct_batch_norm_9)
        self.module_10 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.29(YOLOv6s::nndct_elemwise_add_10)
        self.module_11 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[0]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.31(YOLOv6s::nndct_elemwise_add_11)
        self.module_12 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepConv[0]/Conv2d[conv]/ret.33(YOLOv6s::nndct_conv2d_12)
        self.module_13 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepConv[0]/LeakyReLU[act]/ret.37(YOLOv6s::nndct_leaky_relu_13)
        self.module_14 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.39(YOLOv6s::nndct_conv2d_14)
        self.module_15 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.43(YOLOv6s::nndct_leaky_relu_15)
        self.module_16 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.45(YOLOv6s::nndct_conv2d_16)
        self.module_17 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.49(YOLOv6s::nndct_leaky_relu_17)
        self.module_18 = py_nndct.nn.BatchNorm(num_features=64, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.51(YOLOv6s::nndct_batch_norm_18)
        self.module_19 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.53(YOLOv6s::nndct_elemwise_add_19)
        self.module_20 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.55(YOLOv6s::nndct_elemwise_add_20)
        self.module_21 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.57(YOLOv6s::nndct_conv2d_21)
        self.module_22 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.61(YOLOv6s::nndct_leaky_relu_22)
        self.module_23 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.63(YOLOv6s::nndct_conv2d_23)
        self.module_24 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.67(YOLOv6s::nndct_leaky_relu_24)
        self.module_25 = py_nndct.nn.BatchNorm(num_features=64, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.69(YOLOv6s::nndct_batch_norm_25)
        self.module_26 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.71(YOLOv6s::nndct_elemwise_add_26)
        self.module_27 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[1]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.73(YOLOv6s::nndct_elemwise_add_27)
        self.module_28 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepConv[0]/Conv2d[conv]/ret.75(YOLOv6s::nndct_conv2d_28)
        self.module_29 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepConv[0]/LeakyReLU[act]/ret.79(YOLOv6s::nndct_leaky_relu_29)
        self.module_30 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.81(YOLOv6s::nndct_conv2d_30)
        self.module_31 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.85(YOLOv6s::nndct_leaky_relu_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.87(YOLOv6s::nndct_conv2d_32)
        self.module_33 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.91(YOLOv6s::nndct_leaky_relu_33)
        self.module_34 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.93(YOLOv6s::nndct_batch_norm_34)
        self.module_35 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.95(YOLOv6s::nndct_elemwise_add_35)
        self.module_36 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.97(YOLOv6s::nndct_elemwise_add_36)
        self.module_37 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.99(YOLOv6s::nndct_conv2d_37)
        self.module_38 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.103(YOLOv6s::nndct_leaky_relu_38)
        self.module_39 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.105(YOLOv6s::nndct_conv2d_39)
        self.module_40 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.109(YOLOv6s::nndct_leaky_relu_40)
        self.module_41 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.111(YOLOv6s::nndct_batch_norm_41)
        self.module_42 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.113(YOLOv6s::nndct_elemwise_add_42)
        self.module_43 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.115(YOLOv6s::nndct_elemwise_add_43)
        self.module_44 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/Conv2d[conv]/ret.117(YOLOv6s::nndct_conv2d_44)
        self.module_45 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/LeakyReLU[act]/ret.121(YOLOv6s::nndct_leaky_relu_45)
        self.module_46 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/Conv2d[conv]/ret.123(YOLOv6s::nndct_conv2d_46)
        self.module_47 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/LeakyReLU[act]/ret.127(YOLOv6s::nndct_leaky_relu_47)
        self.module_48 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/BatchNorm2d[bn]/ret.129(YOLOv6s::nndct_batch_norm_48)
        self.module_49 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/ret.131(YOLOv6s::nndct_elemwise_add_49)
        self.module_50 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/ret.133(YOLOv6s::nndct_elemwise_add_50)
        self.module_51 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/Conv2d[conv]/ret.135(YOLOv6s::nndct_conv2d_51)
        self.module_52 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/LeakyReLU[act]/ret.139(YOLOv6s::nndct_leaky_relu_52)
        self.module_53 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/Conv2d[conv]/ret.141(YOLOv6s::nndct_conv2d_53)
        self.module_54 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/LeakyReLU[act]/ret.145(YOLOv6s::nndct_leaky_relu_54)
        self.module_55 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/BatchNorm2d[bn]/ret.147(YOLOv6s::nndct_batch_norm_55)
        self.module_56 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/ret.149(YOLOv6s::nndct_elemwise_add_56)
        self.module_57 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[2]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/ret.151(YOLOv6s::nndct_elemwise_add_57)
        self.module_58 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepConv[0]/Conv2d[conv]/ret.153(YOLOv6s::nndct_conv2d_58)
        self.module_59 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepConv[0]/LeakyReLU[act]/ret.157(YOLOv6s::nndct_leaky_relu_59)
        self.module_60 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.159(YOLOv6s::nndct_conv2d_60)
        self.module_61 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.163(YOLOv6s::nndct_leaky_relu_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.165(YOLOv6s::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.169(YOLOv6s::nndct_leaky_relu_63)
        self.module_64 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.171(YOLOv6s::nndct_batch_norm_64)
        self.module_65 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.173(YOLOv6s::nndct_elemwise_add_65)
        self.module_66 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.175(YOLOv6s::nndct_elemwise_add_66)
        self.module_67 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.177(YOLOv6s::nndct_conv2d_67)
        self.module_68 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.181(YOLOv6s::nndct_leaky_relu_68)
        self.module_69 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.183(YOLOv6s::nndct_conv2d_69)
        self.module_70 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.187(YOLOv6s::nndct_leaky_relu_70)
        self.module_71 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.189(YOLOv6s::nndct_batch_norm_71)
        self.module_72 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.191(YOLOv6s::nndct_elemwise_add_72)
        self.module_73 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.193(YOLOv6s::nndct_elemwise_add_73)
        self.module_74 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/Conv2d[conv]/ret.195(YOLOv6s::nndct_conv2d_74)
        self.module_75 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/LeakyReLU[act]/ret.199(YOLOv6s::nndct_leaky_relu_75)
        self.module_76 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/Conv2d[conv]/ret.201(YOLOv6s::nndct_conv2d_76)
        self.module_77 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/LeakyReLU[act]/ret.205(YOLOv6s::nndct_leaky_relu_77)
        self.module_78 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/BatchNorm2d[bn]/ret.207(YOLOv6s::nndct_batch_norm_78)
        self.module_79 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/ret.209(YOLOv6s::nndct_elemwise_add_79)
        self.module_80 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[2]/ret.211(YOLOv6s::nndct_elemwise_add_80)
        self.module_81 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/Conv2d[conv]/ret.213(YOLOv6s::nndct_conv2d_81)
        self.module_82 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/LeakyReLU[act]/ret.217(YOLOv6s::nndct_leaky_relu_82)
        self.module_83 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/Conv2d[conv]/ret.219(YOLOv6s::nndct_conv2d_83)
        self.module_84 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/LeakyReLU[act]/ret.223(YOLOv6s::nndct_leaky_relu_84)
        self.module_85 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/BatchNorm2d[bn]/ret.225(YOLOv6s::nndct_batch_norm_85)
        self.module_86 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/ret.227(YOLOv6s::nndct_elemwise_add_86)
        self.module_87 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[3]/ret.229(YOLOv6s::nndct_elemwise_add_87)
        self.module_88 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/RepConv[conv3]/Conv2d[conv]/ret.231(YOLOv6s::nndct_conv2d_88)
        self.module_89 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/RepConv[conv3]/LeakyReLU[act]/ret.235(YOLOv6s::nndct_leaky_relu_89)
        self.module_90 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/RepConv[conv1]/Conv2d[conv]/ret.237(YOLOv6s::nndct_conv2d_90)
        self.module_91 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/RepConv[conv1]/LeakyReLU[act]/ret.241(YOLOv6s::nndct_leaky_relu_91)
        self.module_92 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/BatchNorm2d[bn]/ret.243(YOLOv6s::nndct_batch_norm_92)
        self.module_93 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/ret.245(YOLOv6s::nndct_elemwise_add_93)
        self.module_94 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[4]/ret.247(YOLOv6s::nndct_elemwise_add_94)
        self.module_95 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/RepConv[conv3]/Conv2d[conv]/ret.249(YOLOv6s::nndct_conv2d_95)
        self.module_96 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/RepConv[conv3]/LeakyReLU[act]/ret.253(YOLOv6s::nndct_leaky_relu_96)
        self.module_97 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/RepConv[conv1]/Conv2d[conv]/ret.255(YOLOv6s::nndct_conv2d_97)
        self.module_98 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/RepConv[conv1]/LeakyReLU[act]/ret.259(YOLOv6s::nndct_leaky_relu_98)
        self.module_99 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/BatchNorm2d[bn]/ret.261(YOLOv6s::nndct_batch_norm_99)
        self.module_100 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/ret.263(YOLOv6s::nndct_elemwise_add_100)
        self.module_101 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[3]/RepBlock[1]/RepVGG[layers]/ModuleList[5]/ret.265(YOLOv6s::nndct_elemwise_add_101)
        self.module_102 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepConv[0]/Conv2d[conv]/ret.267(YOLOv6s::nndct_conv2d_102)
        self.module_103 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepConv[0]/LeakyReLU[act]/ret.271(YOLOv6s::nndct_leaky_relu_103)
        self.module_104 = py_nndct.nn.Conv2d(in_channels=512, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.273(YOLOv6s::nndct_conv2d_104)
        self.module_105 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.277(YOLOv6s::nndct_leaky_relu_105)
        self.module_106 = py_nndct.nn.Conv2d(in_channels=512, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.279(YOLOv6s::nndct_conv2d_106)
        self.module_107 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.283(YOLOv6s::nndct_leaky_relu_107)
        self.module_108 = py_nndct.nn.BatchNorm(num_features=512, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.285(YOLOv6s::nndct_batch_norm_108)
        self.module_109 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.287(YOLOv6s::nndct_elemwise_add_109)
        self.module_110 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[0]/ret.289(YOLOv6s::nndct_elemwise_add_110)
        self.module_111 = py_nndct.nn.Conv2d(in_channels=512, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.291(YOLOv6s::nndct_conv2d_111)
        self.module_112 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.295(YOLOv6s::nndct_leaky_relu_112)
        self.module_113 = py_nndct.nn.Conv2d(in_channels=512, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.297(YOLOv6s::nndct_conv2d_113)
        self.module_114 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.301(YOLOv6s::nndct_leaky_relu_114)
        self.module_115 = py_nndct.nn.BatchNorm(num_features=512, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.303(YOLOv6s::nndct_batch_norm_115)
        self.module_116 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.305(YOLOv6s::nndct_elemwise_add_116)
        self.module_117 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/EfficientRep[backbone]/Sequential[layers]/ModuleList[4]/RepBlock[1]/RepVGG[layers]/ModuleList[1]/ret.307(YOLOv6s::nndct_elemwise_add_117)
        self.module_118 = py_nndct.nn.Conv2d(in_channels=512, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[reduce_layer0]/Conv2d[conv]/ret.309(YOLOv6s::nndct_conv2d_118)
        self.module_119 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[reduce_layer0]/LeakyReLU[act]/ret.313(YOLOv6s::nndct_leaky_relu_119)
        self.module_120 = py_nndct.nn.Interpolate() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/Upsample[upsamp]/ret.315(YOLOv6s::nndct_resize_120)
        self.module_121 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[cv1]/Conv2d[conv]/ret.317(YOLOv6s::nndct_conv2d_121)
        self.module_122 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[cv1]/LeakyReLU[act]/ret.321(YOLOv6s::nndct_leaky_relu_122)
        self.module_123 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[cv2]/Conv2d[conv]/ret.323(YOLOv6s::nndct_conv2d_123)
        self.module_124 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[cv2]/LeakyReLU[act]/ret.327(YOLOv6s::nndct_leaky_relu_124)
        self.module_125 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[downsamp]/Conv2d[conv]/ret.329(YOLOv6s::nndct_conv2d_125)
        self.module_126 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[downsamp]/LeakyReLU[act]/ret.333(YOLOv6s::nndct_leaky_relu_126)
        self.module_127 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ret.335(YOLOv6s::nndct_concat_127)
        self.module_128 = py_nndct.nn.Conv2d(in_channels=384, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[cv3]/Conv2d[conv]/ret.337(YOLOv6s::nndct_conv2d_128)
        self.module_129 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion0]/ConvBNReLU[cv3]/LeakyReLU[act]/ret.341(YOLOv6s::nndct_leaky_relu_129)
        self.module_130 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.343(YOLOv6s::nndct_conv2d_130)
        self.module_131 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.347(YOLOv6s::nndct_leaky_relu_131)
        self.module_132 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.349(YOLOv6s::nndct_conv2d_132)
        self.module_133 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.353(YOLOv6s::nndct_leaky_relu_133)
        self.module_134 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.355(YOLOv6s::nndct_batch_norm_134)
        self.module_135 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/ret.357(YOLOv6s::nndct_elemwise_add_135)
        self.module_136 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[0]/ret.359(YOLOv6s::nndct_elemwise_add_136)
        self.module_137 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.361(YOLOv6s::nndct_conv2d_137)
        self.module_138 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.365(YOLOv6s::nndct_leaky_relu_138)
        self.module_139 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.367(YOLOv6s::nndct_conv2d_139)
        self.module_140 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.371(YOLOv6s::nndct_leaky_relu_140)
        self.module_141 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.373(YOLOv6s::nndct_batch_norm_141)
        self.module_142 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/ret.375(YOLOv6s::nndct_elemwise_add_142)
        self.module_143 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[1]/ret.377(YOLOv6s::nndct_elemwise_add_143)
        self.module_144 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/Conv2d[conv]/ret.379(YOLOv6s::nndct_conv2d_144)
        self.module_145 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/LeakyReLU[act]/ret.383(YOLOv6s::nndct_leaky_relu_145)
        self.module_146 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/Conv2d[conv]/ret.385(YOLOv6s::nndct_conv2d_146)
        self.module_147 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/LeakyReLU[act]/ret.389(YOLOv6s::nndct_leaky_relu_147)
        self.module_148 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/BatchNorm2d[bn]/ret.391(YOLOv6s::nndct_batch_norm_148)
        self.module_149 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/ret.393(YOLOv6s::nndct_elemwise_add_149)
        self.module_150 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[2]/ret.395(YOLOv6s::nndct_elemwise_add_150)
        self.module_151 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/Conv2d[conv]/ret.397(YOLOv6s::nndct_conv2d_151)
        self.module_152 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/LeakyReLU[act]/ret.401(YOLOv6s::nndct_leaky_relu_152)
        self.module_153 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/Conv2d[conv]/ret.403(YOLOv6s::nndct_conv2d_153)
        self.module_154 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/LeakyReLU[act]/ret.407(YOLOv6s::nndct_leaky_relu_154)
        self.module_155 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/BatchNorm2d[bn]/ret.409(YOLOv6s::nndct_batch_norm_155)
        self.module_156 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/ret.411(YOLOv6s::nndct_elemwise_add_156)
        self.module_157 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep0]/RepVGG[layers]/ModuleList[3]/ret.413(YOLOv6s::nndct_elemwise_add_157)
        self.module_158 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[reduce_layer1]/Conv2d[conv]/ret.415(YOLOv6s::nndct_conv2d_158)
        self.module_159 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[reduce_layer1]/LeakyReLU[act]/ret.419(YOLOv6s::nndct_leaky_relu_159)
        self.module_160 = py_nndct.nn.Interpolate() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/Upsample[upsamp]/ret.421(YOLOv6s::nndct_resize_160)
        self.module_161 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[cv1]/Conv2d[conv]/ret.423(YOLOv6s::nndct_conv2d_161)
        self.module_162 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[cv1]/LeakyReLU[act]/ret.427(YOLOv6s::nndct_leaky_relu_162)
        self.module_163 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[cv2]/Conv2d[conv]/ret.429(YOLOv6s::nndct_conv2d_163)
        self.module_164 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[cv2]/LeakyReLU[act]/ret.433(YOLOv6s::nndct_leaky_relu_164)
        self.module_165 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[downsamp]/Conv2d[conv]/ret.435(YOLOv6s::nndct_conv2d_165)
        self.module_166 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[downsamp]/LeakyReLU[act]/ret.439(YOLOv6s::nndct_leaky_relu_166)
        self.module_167 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ret.441(YOLOv6s::nndct_concat_167)
        self.module_168 = py_nndct.nn.Conv2d(in_channels=192, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[cv3]/Conv2d[conv]/ret.443(YOLOv6s::nndct_conv2d_168)
        self.module_169 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/BiFusion[bifusion1]/ConvBNReLU[cv3]/LeakyReLU[act]/ret.447(YOLOv6s::nndct_leaky_relu_169)
        self.module_170 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.449(YOLOv6s::nndct_conv2d_170)
        self.module_171 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.453(YOLOv6s::nndct_leaky_relu_171)
        self.module_172 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.455(YOLOv6s::nndct_conv2d_172)
        self.module_173 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.459(YOLOv6s::nndct_leaky_relu_173)
        self.module_174 = py_nndct.nn.BatchNorm(num_features=64, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.461(YOLOv6s::nndct_batch_norm_174)
        self.module_175 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/ret.463(YOLOv6s::nndct_elemwise_add_175)
        self.module_176 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[0]/ret.465(YOLOv6s::nndct_elemwise_add_176)
        self.module_177 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.467(YOLOv6s::nndct_conv2d_177)
        self.module_178 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.471(YOLOv6s::nndct_leaky_relu_178)
        self.module_179 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.473(YOLOv6s::nndct_conv2d_179)
        self.module_180 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.477(YOLOv6s::nndct_leaky_relu_180)
        self.module_181 = py_nndct.nn.BatchNorm(num_features=64, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.479(YOLOv6s::nndct_batch_norm_181)
        self.module_182 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/ret.481(YOLOv6s::nndct_elemwise_add_182)
        self.module_183 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[1]/ret.483(YOLOv6s::nndct_elemwise_add_183)
        self.module_184 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/Conv2d[conv]/ret.485(YOLOv6s::nndct_conv2d_184)
        self.module_185 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/LeakyReLU[act]/ret.489(YOLOv6s::nndct_leaky_relu_185)
        self.module_186 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/Conv2d[conv]/ret.491(YOLOv6s::nndct_conv2d_186)
        self.module_187 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/LeakyReLU[act]/ret.495(YOLOv6s::nndct_leaky_relu_187)
        self.module_188 = py_nndct.nn.BatchNorm(num_features=64, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/BatchNorm2d[bn]/ret.497(YOLOv6s::nndct_batch_norm_188)
        self.module_189 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/ret.499(YOLOv6s::nndct_elemwise_add_189)
        self.module_190 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[2]/ret.501(YOLOv6s::nndct_elemwise_add_190)
        self.module_191 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/Conv2d[conv]/ret.503(YOLOv6s::nndct_conv2d_191)
        self.module_192 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/LeakyReLU[act]/ret.507(YOLOv6s::nndct_leaky_relu_192)
        self.module_193 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/Conv2d[conv]/ret.509(YOLOv6s::nndct_conv2d_193)
        self.module_194 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/LeakyReLU[act]/ret.513(YOLOv6s::nndct_leaky_relu_194)
        self.module_195 = py_nndct.nn.BatchNorm(num_features=64, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/BatchNorm2d[bn]/ret.515(YOLOv6s::nndct_batch_norm_195)
        self.module_196 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/ret.517(YOLOv6s::nndct_elemwise_add_196)
        self.module_197 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep1]/RepVGG[layers]/ModuleList[3]/ret.519(YOLOv6s::nndct_elemwise_add_197)
        self.module_198 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[downsamp2]/Conv2d[conv]/ret.521(YOLOv6s::nndct_conv2d_198)
        self.module_199 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[downsamp2]/LeakyReLU[act]/ret.525(YOLOv6s::nndct_leaky_relu_199)
        self.module_200 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ret.527(YOLOv6s::nndct_concat_200)
        self.module_201 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.529(YOLOv6s::nndct_conv2d_201)
        self.module_202 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.533(YOLOv6s::nndct_leaky_relu_202)
        self.module_203 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.535(YOLOv6s::nndct_conv2d_203)
        self.module_204 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.539(YOLOv6s::nndct_leaky_relu_204)
        self.module_205 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.541(YOLOv6s::nndct_batch_norm_205)
        self.module_206 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/ret.543(YOLOv6s::nndct_elemwise_add_206)
        self.module_207 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[0]/ret.545(YOLOv6s::nndct_elemwise_add_207)
        self.module_208 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.547(YOLOv6s::nndct_conv2d_208)
        self.module_209 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.551(YOLOv6s::nndct_leaky_relu_209)
        self.module_210 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.553(YOLOv6s::nndct_conv2d_210)
        self.module_211 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.557(YOLOv6s::nndct_leaky_relu_211)
        self.module_212 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.559(YOLOv6s::nndct_batch_norm_212)
        self.module_213 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/ret.561(YOLOv6s::nndct_elemwise_add_213)
        self.module_214 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[1]/ret.563(YOLOv6s::nndct_elemwise_add_214)
        self.module_215 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/Conv2d[conv]/ret.565(YOLOv6s::nndct_conv2d_215)
        self.module_216 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/LeakyReLU[act]/ret.569(YOLOv6s::nndct_leaky_relu_216)
        self.module_217 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/Conv2d[conv]/ret.571(YOLOv6s::nndct_conv2d_217)
        self.module_218 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/LeakyReLU[act]/ret.575(YOLOv6s::nndct_leaky_relu_218)
        self.module_219 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/BatchNorm2d[bn]/ret.577(YOLOv6s::nndct_batch_norm_219)
        self.module_220 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/ret.579(YOLOv6s::nndct_elemwise_add_220)
        self.module_221 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[2]/ret.581(YOLOv6s::nndct_elemwise_add_221)
        self.module_222 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/Conv2d[conv]/ret.583(YOLOv6s::nndct_conv2d_222)
        self.module_223 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/LeakyReLU[act]/ret.587(YOLOv6s::nndct_leaky_relu_223)
        self.module_224 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/Conv2d[conv]/ret.589(YOLOv6s::nndct_conv2d_224)
        self.module_225 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/LeakyReLU[act]/ret.593(YOLOv6s::nndct_leaky_relu_225)
        self.module_226 = py_nndct.nn.BatchNorm(num_features=128, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/BatchNorm2d[bn]/ret.595(YOLOv6s::nndct_batch_norm_226)
        self.module_227 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/ret.597(YOLOv6s::nndct_elemwise_add_227)
        self.module_228 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep2]/RepVGG[layers]/ModuleList[3]/ret.599(YOLOv6s::nndct_elemwise_add_228)
        self.module_229 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[downsamp1]/Conv2d[conv]/ret.601(YOLOv6s::nndct_conv2d_229)
        self.module_230 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ConvBNReLU[downsamp1]/LeakyReLU[act]/ret.605(YOLOv6s::nndct_leaky_relu_230)
        self.module_231 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/ret.607(YOLOv6s::nndct_concat_231)
        self.module_232 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/Conv2d[conv]/ret.609(YOLOv6s::nndct_conv2d_232)
        self.module_233 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/RepConv[conv3]/LeakyReLU[act]/ret.613(YOLOv6s::nndct_leaky_relu_233)
        self.module_234 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/Conv2d[conv]/ret.615(YOLOv6s::nndct_conv2d_234)
        self.module_235 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/RepConv[conv1]/LeakyReLU[act]/ret.619(YOLOv6s::nndct_leaky_relu_235)
        self.module_236 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/BatchNorm2d[bn]/ret.621(YOLOv6s::nndct_batch_norm_236)
        self.module_237 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/ret.623(YOLOv6s::nndct_elemwise_add_237)
        self.module_238 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[0]/ret.625(YOLOv6s::nndct_elemwise_add_238)
        self.module_239 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/Conv2d[conv]/ret.627(YOLOv6s::nndct_conv2d_239)
        self.module_240 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/RepConv[conv3]/LeakyReLU[act]/ret.631(YOLOv6s::nndct_leaky_relu_240)
        self.module_241 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/Conv2d[conv]/ret.633(YOLOv6s::nndct_conv2d_241)
        self.module_242 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/RepConv[conv1]/LeakyReLU[act]/ret.637(YOLOv6s::nndct_leaky_relu_242)
        self.module_243 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/BatchNorm2d[bn]/ret.639(YOLOv6s::nndct_batch_norm_243)
        self.module_244 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/ret.641(YOLOv6s::nndct_elemwise_add_244)
        self.module_245 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[1]/ret.643(YOLOv6s::nndct_elemwise_add_245)
        self.module_246 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/Conv2d[conv]/ret.645(YOLOv6s::nndct_conv2d_246)
        self.module_247 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/RepConv[conv3]/LeakyReLU[act]/ret.649(YOLOv6s::nndct_leaky_relu_247)
        self.module_248 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/Conv2d[conv]/ret.651(YOLOv6s::nndct_conv2d_248)
        self.module_249 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/RepConv[conv1]/LeakyReLU[act]/ret.655(YOLOv6s::nndct_leaky_relu_249)
        self.module_250 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/BatchNorm2d[bn]/ret.657(YOLOv6s::nndct_batch_norm_250)
        self.module_251 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/ret.659(YOLOv6s::nndct_elemwise_add_251)
        self.module_252 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[2]/ret.661(YOLOv6s::nndct_elemwise_add_252)
        self.module_253 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/Conv2d[conv]/ret.663(YOLOv6s::nndct_conv2d_253)
        self.module_254 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/RepConv[conv3]/LeakyReLU[act]/ret.667(YOLOv6s::nndct_leaky_relu_254)
        self.module_255 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/Conv2d[conv]/ret.669(YOLOv6s::nndct_conv2d_255)
        self.module_256 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/RepConv[conv1]/LeakyReLU[act]/ret.673(YOLOv6s::nndct_leaky_relu_256)
        self.module_257 = py_nndct.nn.BatchNorm(num_features=256, eps=0.0, momentum=0.1) #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/BatchNorm2d[bn]/ret.675(YOLOv6s::nndct_batch_norm_257)
        self.module_258 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/ret.677(YOLOv6s::nndct_elemwise_add_258)
        self.module_259 = py_nndct.nn.Add() #YOLOv6s::YOLOv6s/RepBiPAN[neck]/RepBlock[rep3]/RepVGG[layers]/ModuleList[3]/ret.679(YOLOv6s::nndct_elemwise_add_259)
        self.module_260 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[stem0]/Conv2d[conv]/ret.681(YOLOv6s::nndct_conv2d_260)
        self.module_261 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[stem0]/LeakyReLU[act]/ret.685(YOLOv6s::nndct_leaky_relu_261)
        self.module_262 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_conv0]/Conv2d[conv]/ret.687(YOLOv6s::nndct_conv2d_262)
        self.module_263 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_conv0]/LeakyReLU[act]/ret.691(YOLOv6s::nndct_leaky_relu_263)
        self.module_264 = py_nndct.nn.Conv2d(in_channels=256, out_channels=20, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_pred0]/Conv2d[conv]/ret.693(YOLOv6s::nndct_conv2d_264)
        self.module_265 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_pred0]/LeakyReLU[act]/ret.697(YOLOv6s::nndct_leaky_relu_265)
        self.module_266 = py_nndct.nn.Conv2d(in_channels=256, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_conv0]/Conv2d[conv]/ret.699(YOLOv6s::nndct_conv2d_266)
        self.module_267 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_conv0]/LeakyReLU[act]/ret.703(YOLOv6s::nndct_leaky_relu_267)
        self.module_268 = py_nndct.nn.Conv2d(in_channels=256, out_channels=5, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_pred0]/Conv2d[conv]/ret.705(YOLOv6s::nndct_conv2d_268)
        self.module_269 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_pred0]/LeakyReLU[act]/ret.709(YOLOv6s::nndct_leaky_relu_269)
        self.module_270 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[stem1]/Conv2d[conv]/ret.711(YOLOv6s::nndct_conv2d_270)
        self.module_271 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[stem1]/LeakyReLU[act]/ret.715(YOLOv6s::nndct_leaky_relu_271)
        self.module_272 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_conv1]/Conv2d[conv]/ret.717(YOLOv6s::nndct_conv2d_272)
        self.module_273 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_conv1]/LeakyReLU[act]/ret.721(YOLOv6s::nndct_leaky_relu_273)
        self.module_274 = py_nndct.nn.Conv2d(in_channels=128, out_channels=20, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_pred1]/Conv2d[conv]/ret.723(YOLOv6s::nndct_conv2d_274)
        self.module_275 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_pred1]/LeakyReLU[act]/ret.727(YOLOv6s::nndct_leaky_relu_275)
        self.module_276 = py_nndct.nn.Conv2d(in_channels=128, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_conv1]/Conv2d[conv]/ret.729(YOLOv6s::nndct_conv2d_276)
        self.module_277 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_conv1]/LeakyReLU[act]/ret.733(YOLOv6s::nndct_leaky_relu_277)
        self.module_278 = py_nndct.nn.Conv2d(in_channels=128, out_channels=5, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_pred1]/Conv2d[conv]/ret.735(YOLOv6s::nndct_conv2d_278)
        self.module_279 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_pred1]/LeakyReLU[act]/ret.739(YOLOv6s::nndct_leaky_relu_279)
        self.module_280 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[stem2]/Conv2d[conv]/ret.741(YOLOv6s::nndct_conv2d_280)
        self.module_281 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[stem2]/LeakyReLU[act]/ret.745(YOLOv6s::nndct_leaky_relu_281)
        self.module_282 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_conv2]/Conv2d[conv]/ret.747(YOLOv6s::nndct_conv2d_282)
        self.module_283 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_conv2]/LeakyReLU[act]/ret.751(YOLOv6s::nndct_leaky_relu_283)
        self.module_284 = py_nndct.nn.Conv2d(in_channels=64, out_channels=20, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_pred2]/Conv2d[conv]/ret.753(YOLOv6s::nndct_conv2d_284)
        self.module_285 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[cls_pred2]/LeakyReLU[act]/ret.757(YOLOv6s::nndct_leaky_relu_285)
        self.module_286 = py_nndct.nn.Conv2d(in_channels=64, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_conv2]/Conv2d[conv]/ret.759(YOLOv6s::nndct_conv2d_286)
        self.module_287 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_conv2]/LeakyReLU[act]/ret.763(YOLOv6s::nndct_leaky_relu_287)
        self.module_288 = py_nndct.nn.Conv2d(in_channels=64, out_channels=5, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_pred2]/Conv2d[conv]/ret.765(YOLOv6s::nndct_conv2d_288)
        self.module_289 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv6s::YOLOv6s/DetectionHead[head]/ConvBNReLU[reg_pred2]/LeakyReLU[act]/ret.769(YOLOv6s::nndct_leaky_relu_289)
        self.module_290 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/DetectionHead[head]/ret.771(YOLOv6s::nndct_concat_290)
        self.module_291 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/DetectionHead[head]/ret.773(YOLOv6s::nndct_concat_291)
        self.module_292 = py_nndct.nn.Cat() #YOLOv6s::YOLOv6s/DetectionHead[head]/ret.775(YOLOv6s::nndct_concat_292)
        self.module_293 = py_nndct.nn.Module('nndct_permute') #YOLOv6s::YOLOv6s/DetectionHead[head]/ret.777(YOLOv6s::nndct_permute_293)
        self.module_294 = py_nndct.nn.Module('nndct_permute') #YOLOv6s::YOLOv6s/DetectionHead[head]/ret.779(YOLOv6s::nndct_permute_294)
        self.module_295 = py_nndct.nn.Module('nndct_permute') #YOLOv6s::YOLOv6s/DetectionHead[head]/ret(YOLOv6s::nndct_permute_295)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_5 = self.module_5(output_module_0)
        output_module_5 = self.module_6(output_module_5)
        output_module_7 = self.module_7(output_module_0)
        output_module_7 = self.module_8(output_module_7)
        output_module_9 = self.module_9(output_module_0)
        output_module_5 = self.module_10(input=output_module_5, other=output_module_7, alpha=1)
        output_module_5 = self.module_11(input=output_module_5, other=output_module_9, alpha=1)
        output_module_5 = self.module_12(output_module_5)
        output_module_5 = self.module_13(output_module_5)
        output_module_14 = self.module_14(output_module_5)
        output_module_14 = self.module_15(output_module_14)
        output_module_16 = self.module_16(output_module_5)
        output_module_16 = self.module_17(output_module_16)
        output_module_18 = self.module_18(output_module_5)
        output_module_14 = self.module_19(input=output_module_14, other=output_module_16, alpha=1)
        output_module_14 = self.module_20(input=output_module_14, other=output_module_18, alpha=1)
        output_module_21 = self.module_21(output_module_14)
        output_module_21 = self.module_22(output_module_21)
        output_module_23 = self.module_23(output_module_14)
        output_module_23 = self.module_24(output_module_23)
        output_module_25 = self.module_25(output_module_14)
        output_module_21 = self.module_26(input=output_module_21, other=output_module_23, alpha=1)
        output_module_21 = self.module_27(input=output_module_21, other=output_module_25, alpha=1)
        output_module_28 = self.module_28(output_module_21)
        output_module_28 = self.module_29(output_module_28)
        output_module_30 = self.module_30(output_module_28)
        output_module_30 = self.module_31(output_module_30)
        output_module_32 = self.module_32(output_module_28)
        output_module_32 = self.module_33(output_module_32)
        output_module_34 = self.module_34(output_module_28)
        output_module_30 = self.module_35(input=output_module_30, other=output_module_32, alpha=1)
        output_module_30 = self.module_36(input=output_module_30, other=output_module_34, alpha=1)
        output_module_37 = self.module_37(output_module_30)
        output_module_37 = self.module_38(output_module_37)
        output_module_39 = self.module_39(output_module_30)
        output_module_39 = self.module_40(output_module_39)
        output_module_41 = self.module_41(output_module_30)
        output_module_37 = self.module_42(input=output_module_37, other=output_module_39, alpha=1)
        output_module_37 = self.module_43(input=output_module_37, other=output_module_41, alpha=1)
        output_module_44 = self.module_44(output_module_37)
        output_module_44 = self.module_45(output_module_44)
        output_module_46 = self.module_46(output_module_37)
        output_module_46 = self.module_47(output_module_46)
        output_module_48 = self.module_48(output_module_37)
        output_module_44 = self.module_49(input=output_module_44, other=output_module_46, alpha=1)
        output_module_44 = self.module_50(input=output_module_44, other=output_module_48, alpha=1)
        output_module_51 = self.module_51(output_module_44)
        output_module_51 = self.module_52(output_module_51)
        output_module_53 = self.module_53(output_module_44)
        output_module_53 = self.module_54(output_module_53)
        output_module_55 = self.module_55(output_module_44)
        output_module_51 = self.module_56(input=output_module_51, other=output_module_53, alpha=1)
        output_module_51 = self.module_57(input=output_module_51, other=output_module_55, alpha=1)
        output_module_58 = self.module_58(output_module_51)
        output_module_58 = self.module_59(output_module_58)
        output_module_60 = self.module_60(output_module_58)
        output_module_60 = self.module_61(output_module_60)
        output_module_62 = self.module_62(output_module_58)
        output_module_62 = self.module_63(output_module_62)
        output_module_64 = self.module_64(output_module_58)
        output_module_60 = self.module_65(input=output_module_60, other=output_module_62, alpha=1)
        output_module_60 = self.module_66(input=output_module_60, other=output_module_64, alpha=1)
        output_module_67 = self.module_67(output_module_60)
        output_module_67 = self.module_68(output_module_67)
        output_module_69 = self.module_69(output_module_60)
        output_module_69 = self.module_70(output_module_69)
        output_module_71 = self.module_71(output_module_60)
        output_module_67 = self.module_72(input=output_module_67, other=output_module_69, alpha=1)
        output_module_67 = self.module_73(input=output_module_67, other=output_module_71, alpha=1)
        output_module_74 = self.module_74(output_module_67)
        output_module_74 = self.module_75(output_module_74)
        output_module_76 = self.module_76(output_module_67)
        output_module_76 = self.module_77(output_module_76)
        output_module_78 = self.module_78(output_module_67)
        output_module_74 = self.module_79(input=output_module_74, other=output_module_76, alpha=1)
        output_module_74 = self.module_80(input=output_module_74, other=output_module_78, alpha=1)
        output_module_81 = self.module_81(output_module_74)
        output_module_81 = self.module_82(output_module_81)
        output_module_83 = self.module_83(output_module_74)
        output_module_83 = self.module_84(output_module_83)
        output_module_85 = self.module_85(output_module_74)
        output_module_81 = self.module_86(input=output_module_81, other=output_module_83, alpha=1)
        output_module_81 = self.module_87(input=output_module_81, other=output_module_85, alpha=1)
        output_module_88 = self.module_88(output_module_81)
        output_module_88 = self.module_89(output_module_88)
        output_module_90 = self.module_90(output_module_81)
        output_module_90 = self.module_91(output_module_90)
        output_module_92 = self.module_92(output_module_81)
        output_module_88 = self.module_93(input=output_module_88, other=output_module_90, alpha=1)
        output_module_88 = self.module_94(input=output_module_88, other=output_module_92, alpha=1)
        output_module_95 = self.module_95(output_module_88)
        output_module_95 = self.module_96(output_module_95)
        output_module_97 = self.module_97(output_module_88)
        output_module_97 = self.module_98(output_module_97)
        output_module_99 = self.module_99(output_module_88)
        output_module_95 = self.module_100(input=output_module_95, other=output_module_97, alpha=1)
        output_module_95 = self.module_101(input=output_module_95, other=output_module_99, alpha=1)
        output_module_102 = self.module_102(output_module_95)
        output_module_102 = self.module_103(output_module_102)
        output_module_104 = self.module_104(output_module_102)
        output_module_104 = self.module_105(output_module_104)
        output_module_106 = self.module_106(output_module_102)
        output_module_106 = self.module_107(output_module_106)
        output_module_108 = self.module_108(output_module_102)
        output_module_104 = self.module_109(input=output_module_104, other=output_module_106, alpha=1)
        output_module_104 = self.module_110(input=output_module_104, other=output_module_108, alpha=1)
        output_module_111 = self.module_111(output_module_104)
        output_module_111 = self.module_112(output_module_111)
        output_module_113 = self.module_113(output_module_104)
        output_module_113 = self.module_114(output_module_113)
        output_module_115 = self.module_115(output_module_104)
        output_module_111 = self.module_116(input=output_module_111, other=output_module_113, alpha=1)
        output_module_111 = self.module_117(input=output_module_111, other=output_module_115, alpha=1)
        output_module_111 = self.module_118(output_module_111)
        output_module_111 = self.module_119(output_module_111)
        output_module_120 = self.module_120(input=output_module_111, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_121 = self.module_121(output_module_95)
        output_module_121 = self.module_122(output_module_121)
        output_module_123 = self.module_123(output_module_51)
        output_module_123 = self.module_124(output_module_123)
        output_module_123 = self.module_125(output_module_123)
        output_module_123 = self.module_126(output_module_123)
        output_module_120 = self.module_127(dim=1, tensors=[output_module_120,output_module_121,output_module_123])
        output_module_120 = self.module_128(output_module_120)
        output_module_120 = self.module_129(output_module_120)
        output_module_130 = self.module_130(output_module_120)
        output_module_130 = self.module_131(output_module_130)
        output_module_132 = self.module_132(output_module_120)
        output_module_132 = self.module_133(output_module_132)
        output_module_134 = self.module_134(output_module_120)
        output_module_130 = self.module_135(input=output_module_130, other=output_module_132, alpha=1)
        output_module_130 = self.module_136(input=output_module_130, other=output_module_134, alpha=1)
        output_module_137 = self.module_137(output_module_130)
        output_module_137 = self.module_138(output_module_137)
        output_module_139 = self.module_139(output_module_130)
        output_module_139 = self.module_140(output_module_139)
        output_module_141 = self.module_141(output_module_130)
        output_module_137 = self.module_142(input=output_module_137, other=output_module_139, alpha=1)
        output_module_137 = self.module_143(input=output_module_137, other=output_module_141, alpha=1)
        output_module_144 = self.module_144(output_module_137)
        output_module_144 = self.module_145(output_module_144)
        output_module_146 = self.module_146(output_module_137)
        output_module_146 = self.module_147(output_module_146)
        output_module_148 = self.module_148(output_module_137)
        output_module_144 = self.module_149(input=output_module_144, other=output_module_146, alpha=1)
        output_module_144 = self.module_150(input=output_module_144, other=output_module_148, alpha=1)
        output_module_151 = self.module_151(output_module_144)
        output_module_151 = self.module_152(output_module_151)
        output_module_153 = self.module_153(output_module_144)
        output_module_153 = self.module_154(output_module_153)
        output_module_155 = self.module_155(output_module_144)
        output_module_151 = self.module_156(input=output_module_151, other=output_module_153, alpha=1)
        output_module_151 = self.module_157(input=output_module_151, other=output_module_155, alpha=1)
        output_module_151 = self.module_158(output_module_151)
        output_module_151 = self.module_159(output_module_151)
        output_module_160 = self.module_160(input=output_module_151, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_161 = self.module_161(output_module_51)
        output_module_161 = self.module_162(output_module_161)
        output_module_163 = self.module_163(output_module_21)
        output_module_163 = self.module_164(output_module_163)
        output_module_163 = self.module_165(output_module_163)
        output_module_163 = self.module_166(output_module_163)
        output_module_160 = self.module_167(dim=1, tensors=[output_module_160,output_module_161,output_module_163])
        output_module_160 = self.module_168(output_module_160)
        output_module_160 = self.module_169(output_module_160)
        output_module_170 = self.module_170(output_module_160)
        output_module_170 = self.module_171(output_module_170)
        output_module_172 = self.module_172(output_module_160)
        output_module_172 = self.module_173(output_module_172)
        output_module_174 = self.module_174(output_module_160)
        output_module_170 = self.module_175(input=output_module_170, other=output_module_172, alpha=1)
        output_module_170 = self.module_176(input=output_module_170, other=output_module_174, alpha=1)
        output_module_177 = self.module_177(output_module_170)
        output_module_177 = self.module_178(output_module_177)
        output_module_179 = self.module_179(output_module_170)
        output_module_179 = self.module_180(output_module_179)
        output_module_181 = self.module_181(output_module_170)
        output_module_177 = self.module_182(input=output_module_177, other=output_module_179, alpha=1)
        output_module_177 = self.module_183(input=output_module_177, other=output_module_181, alpha=1)
        output_module_184 = self.module_184(output_module_177)
        output_module_184 = self.module_185(output_module_184)
        output_module_186 = self.module_186(output_module_177)
        output_module_186 = self.module_187(output_module_186)
        output_module_188 = self.module_188(output_module_177)
        output_module_184 = self.module_189(input=output_module_184, other=output_module_186, alpha=1)
        output_module_184 = self.module_190(input=output_module_184, other=output_module_188, alpha=1)
        output_module_191 = self.module_191(output_module_184)
        output_module_191 = self.module_192(output_module_191)
        output_module_193 = self.module_193(output_module_184)
        output_module_193 = self.module_194(output_module_193)
        output_module_195 = self.module_195(output_module_184)
        output_module_191 = self.module_196(input=output_module_191, other=output_module_193, alpha=1)
        output_module_191 = self.module_197(input=output_module_191, other=output_module_195, alpha=1)
        output_module_198 = self.module_198(output_module_191)
        output_module_198 = self.module_199(output_module_198)
        output_module_198 = self.module_200(dim=1, tensors=[output_module_198,output_module_151])
        output_module_201 = self.module_201(output_module_198)
        output_module_201 = self.module_202(output_module_201)
        output_module_203 = self.module_203(output_module_198)
        output_module_203 = self.module_204(output_module_203)
        output_module_205 = self.module_205(output_module_198)
        output_module_201 = self.module_206(input=output_module_201, other=output_module_203, alpha=1)
        output_module_201 = self.module_207(input=output_module_201, other=output_module_205, alpha=1)
        output_module_208 = self.module_208(output_module_201)
        output_module_208 = self.module_209(output_module_208)
        output_module_210 = self.module_210(output_module_201)
        output_module_210 = self.module_211(output_module_210)
        output_module_212 = self.module_212(output_module_201)
        output_module_208 = self.module_213(input=output_module_208, other=output_module_210, alpha=1)
        output_module_208 = self.module_214(input=output_module_208, other=output_module_212, alpha=1)
        output_module_215 = self.module_215(output_module_208)
        output_module_215 = self.module_216(output_module_215)
        output_module_217 = self.module_217(output_module_208)
        output_module_217 = self.module_218(output_module_217)
        output_module_219 = self.module_219(output_module_208)
        output_module_215 = self.module_220(input=output_module_215, other=output_module_217, alpha=1)
        output_module_215 = self.module_221(input=output_module_215, other=output_module_219, alpha=1)
        output_module_222 = self.module_222(output_module_215)
        output_module_222 = self.module_223(output_module_222)
        output_module_224 = self.module_224(output_module_215)
        output_module_224 = self.module_225(output_module_224)
        output_module_226 = self.module_226(output_module_215)
        output_module_222 = self.module_227(input=output_module_222, other=output_module_224, alpha=1)
        output_module_222 = self.module_228(input=output_module_222, other=output_module_226, alpha=1)
        output_module_229 = self.module_229(output_module_222)
        output_module_229 = self.module_230(output_module_229)
        output_module_229 = self.module_231(dim=1, tensors=[output_module_229,output_module_111])
        output_module_232 = self.module_232(output_module_229)
        output_module_232 = self.module_233(output_module_232)
        output_module_234 = self.module_234(output_module_229)
        output_module_234 = self.module_235(output_module_234)
        output_module_236 = self.module_236(output_module_229)
        output_module_232 = self.module_237(input=output_module_232, other=output_module_234, alpha=1)
        output_module_232 = self.module_238(input=output_module_232, other=output_module_236, alpha=1)
        output_module_239 = self.module_239(output_module_232)
        output_module_239 = self.module_240(output_module_239)
        output_module_241 = self.module_241(output_module_232)
        output_module_241 = self.module_242(output_module_241)
        output_module_243 = self.module_243(output_module_232)
        output_module_239 = self.module_244(input=output_module_239, other=output_module_241, alpha=1)
        output_module_239 = self.module_245(input=output_module_239, other=output_module_243, alpha=1)
        output_module_246 = self.module_246(output_module_239)
        output_module_246 = self.module_247(output_module_246)
        output_module_248 = self.module_248(output_module_239)
        output_module_248 = self.module_249(output_module_248)
        output_module_250 = self.module_250(output_module_239)
        output_module_246 = self.module_251(input=output_module_246, other=output_module_248, alpha=1)
        output_module_246 = self.module_252(input=output_module_246, other=output_module_250, alpha=1)
        output_module_253 = self.module_253(output_module_246)
        output_module_253 = self.module_254(output_module_253)
        output_module_255 = self.module_255(output_module_246)
        output_module_255 = self.module_256(output_module_255)
        output_module_257 = self.module_257(output_module_246)
        output_module_253 = self.module_258(input=output_module_253, other=output_module_255, alpha=1)
        output_module_253 = self.module_259(input=output_module_253, other=output_module_257, alpha=1)
        output_module_253 = self.module_260(output_module_253)
        output_module_253 = self.module_261(output_module_253)
        output_module_262 = self.module_262(output_module_253)
        output_module_262 = self.module_263(output_module_262)
        output_module_262 = self.module_264(output_module_262)
        output_module_262 = self.module_265(output_module_262)
        output_module_266 = self.module_266(output_module_253)
        output_module_266 = self.module_267(output_module_266)
        output_module_266 = self.module_268(output_module_266)
        output_module_266 = self.module_269(output_module_266)
        output_module_270 = self.module_270(output_module_222)
        output_module_270 = self.module_271(output_module_270)
        output_module_272 = self.module_272(output_module_270)
        output_module_272 = self.module_273(output_module_272)
        output_module_272 = self.module_274(output_module_272)
        output_module_272 = self.module_275(output_module_272)
        output_module_276 = self.module_276(output_module_270)
        output_module_276 = self.module_277(output_module_276)
        output_module_276 = self.module_278(output_module_276)
        output_module_276 = self.module_279(output_module_276)
        output_module_280 = self.module_280(output_module_191)
        output_module_280 = self.module_281(output_module_280)
        output_module_282 = self.module_282(output_module_280)
        output_module_282 = self.module_283(output_module_282)
        output_module_282 = self.module_284(output_module_282)
        output_module_282 = self.module_285(output_module_282)
        output_module_286 = self.module_286(output_module_280)
        output_module_286 = self.module_287(output_module_286)
        output_module_286 = self.module_288(output_module_286)
        output_module_286 = self.module_289(output_module_286)
        output_module_262 = self.module_290(dim=1, tensors=[output_module_262,output_module_266])
        output_module_272 = self.module_291(dim=1, tensors=[output_module_272,output_module_276])
        output_module_282 = self.module_292(dim=1, tensors=[output_module_282,output_module_286])
        output_module_262 = self.module_293(dims=[0,2,3,1], input=output_module_262)
        output_module_272 = self.module_294(dims=[0,2,3,1], input=output_module_272)
        output_module_282 = self.module_295(dims=[0,2,3,1], input=output_module_282)
        return (output_module_262,output_module_272,output_module_282)
